upstream_package_name: yggdrasil
downstream_package_name: yggdrasil
specfile_path: out/yggdrasil.spec

srpm_build_deps:
  - bash-completion
  - gawk
  - git-core
  - golang
  - meson
  - 'pkgconfig(dbus-1)'
  - 'pkgconfig(systemd)'
  - rpm-build

actions:
  post-upstream-clone:
    - mkdir out
    - meson setup builddir -Dbuild_srpm=True -Dvendor=True -Dexamples=True
    - meson compile srpm -C builddir
    - bash -c 'mv builddir/dist/srpm/* out/'
  get-current-version:
    - awk '/^Version:/ {print $2;}' out/yggdrasil.spec
  create-archive:
    - bash -c 'echo out/yggdrasil-*.tar.*'
  fix-spec-file:
    - echo 'nothing to fix'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-8
      - centos-stream-9
      - fedora-all
      - rhel-8
      - rhel-9
