upstream_package_name: yggdrasil
downstream_package_name: yggdrasil
specfile_path: yggdrasil.spec

srpm_build_deps:
  - bash-completion
  - gawk
  - git-core
  - golang
  - rpm-build
  - "pkgconfig(systemd)"

actions:
  post-upstream-clone:
    - make yggdrasil.spec
    - make dist
  get-current-version:
    - awk '/^Version:/ {print $2;}' yggdrasil.spec
  create-archive:
    - bash -c 'echo yggdrasil-*.tar.*'

jobs:
  - job: copr_build
    trigger: pull_request
    identifier: "pr_build/el9"
    additional_repos:
      - "copr://@yggdrasil/el9"
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - rhel-9-aarch64
      - rhel-9-x86_64

  - job: copr_build
    trigger: pull_request
    identifier: "pr_build/el8"
    additional_repos:
      - "copr://@yggdrasil/el8"
    targets:
      - rhel-8-aarch64
      - rhel-8-x86_64

  - job: copr_build
    trigger: commit
    identifier: "build/el9"
    additional_repos:
      - "copr://@yggdrasil/el9"
    branch: "yggdrasil-0.2"
    owner: "@yggdrasil"
    project: el9
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - rhel-9-aarch64
      - rhel-9-x86_64

  - job: copr_build
    trigger: commit
    identifier: "build/el8"
    additional_repos:
      - "copr://@yggdrasil/el8"
    branch: "yggdrasil-0.2"
    owner: "@yggdrasil"
    project: el8
    targets:
      - rhel-8-aarch64
      - rhel-8-x86_64
