upstream_package_name: yggdrasil
downstream_package_name: yggdrasil
specfile_path: yggdrasil.spec

srpm_build_deps:
  - bash-completion
  - gawk
  - git-core
  - golang
  - rpm-build
  - "pkgconfig(systemd)"

actions:
  post-upstream-clone:
    - make yggdrasil.spec
    - make dist
  get-current-version:
    - awk '/^Version:/ {print $2;}' yggdrasil.spec
  create-archive:
    - bash -c 'echo yggdrasil-*.tar.*'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-8
      - centos-stream-9
      - fedora-all
      - rhel-8
      - rhel-9

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-8
      - centos-stream-9
      - rhel-8
      - rhel-9
