upstream_package_name: yggdrasil
downstream_package_name: rhc
specfile_path: rhc.spec

srpm_build_deps:
  - bash-completion
  - gawk
  - git-core
  - golang
  - rpm-build
  - "pkgconfig(systemd)"

actions:
  post-upstream-clone:
    - curl -O https://raw.githubusercontent.com/RedHatInsights/rhc/refs/heads/release-0.2/rhc.spec.in
    - bash -c "make LONGNAME=rhc BRANDNAME=rhc SHORTNAME=rhc PKGNAME=rhc TOPICPREFIX=redhat/insights rhc.spec"
  get-current-version:
    - awk '/^VERSION/ {print $3;}' Makefile
  create-archive:
    - curl -LO https://github.com/RedHatInsights/rhc/releases/download/0.2.6/rhc-0.2.6.tar.gz
    - curl -LO https://github.com/RedHatInsights/yggdrasil-worker-package-manager/releases/download/0.1.0/yggdrasil-worker-package-manager-0.1.0.tar.gz
    - make dist
    - bash -c "echo yggdrasil-${PACKIT_PROJECT_VERSION}.tar.gz"
  fix-spec-file:
    - bash -c "sed -i -r \"s/Source1:.*/Source1:\ yggdrasil-${PACKIT_PROJECT_VERSION}.tar.gz/\" rhc.spec"
    - bash -c "sed -i -r \"s#cd %\{_builddir\}/%\{name\}/yggdrasil-0.2.2#cd %\{_builddir\}/%\{name\}/yggdrasil-${PACKIT_PROJECT_VERSION}#g\" rhc.spec"

jobs:
  - job: copr_build
    trigger: pull_request
    identifier: "pr_build/el9"
    additional_repos:
      - "copr://@yggdrasil/el9"
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - rhel-9-aarch64
      - rhel-9-x86_64

  - job: copr_build
    trigger: pull_request
    identifier: "pr_build/el8"
    additional_repos:
      - "copr://@yggdrasil/el8"
    targets:
      - rhel-8-aarch64
      - rhel-8-x86_64

  - job: copr_build
    trigger: commit
    identifier: "build/el9"
    additional_repos:
      - "copr://@yggdrasil/el9"
    branch: "yggdrasil-0.2"
    owner: "@yggdrasil"
    project: el9
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - rhel-9-aarch64
      - rhel-9-x86_64

  - job: copr_build
    trigger: commit
    identifier: "build/el8"
    additional_repos:
      - "copr://@yggdrasil/el8"
    branch: "yggdrasil-0.2"
    owner: "@yggdrasil"
    project: el8
    targets:
      - rhel-8-aarch64
      - rhel-8-x86_64
