upstream_package_name: yggdrasil
downstream_package_name: yggdrasil
specfile_path: builddir/dist/srpm/yggdrasil.spec
upstream_tag_template: v{version}

packages:
  yggdrasil-centos:
    pkg_tool: centpkg
    specfile_path: yggdrasil.spec
    actions:
      post-upstream-clone:
        - wget https://gitlab.com/redhat/centos-stream/rpms/yggdrasil/-/raw/c10s/yggdrasil.spec
        - meson setup builddir -Dbuild_srpm=True -Dvendor=True -Dexamples=True --wipe
        - meson compile tarball -C builddir
      get-current-version:
        - awk '/^Version:/ {print $2;}' yggdrasil.spec
      create-archive:
        - bash -c 'echo builddir/dist/srpm/yggdrasil-*.tar.*'
      fix-spec-file:
        - bash -c 'echo "No action needed"'
  yggdrasil-fedora:
    pkg_tool: fedpkg
    specfile_path: yggdrasil.spec
    actions:
      post-upstream-clone:
        - wget https://src.fedoraproject.org/rpms/yggdrasil/raw/rawhide/f/yggdrasil.spec
        - meson setup builddir -Dbuild_srpm=True -Dvendor=True -Dexamples=True --wipe
        - meson compile tarball -C builddir
      get-current-version:
        - awk '/^Version:/ {print $2;}' yggdrasil.spec
      create-archive:
        - bash -c 'echo builddir/dist/srpm/yggdrasil-*.tar.*'
      fix-spec-file:
        - bash -c 'echo "No action needed"'

srpm_build_deps:
  - bash-completion
  - gawk
  - git-core
  - golang
  - go-rpm-macros
  - meson
  - "pkgconfig(dbus-1)"
  - "pkgconfig(systemd)"
  - rpm-build
  - wget

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [yggdrasil-fedora]
    identifier: "build/pr/fedora"
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - fedora-all

  - job: copr_build
    trigger: pull_request
    packages: [yggdrasil-centos]
    identifier: "build/pr/centos-stream"
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-9
      - centos-stream-10
      - rhel-8
      - rhel-9

  - job: copr_build
    trigger: commit
    packages: [yggdrasil-fedora]
    identifier: "build/latest/fedora"
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    packages: [yggdrasil-centos]
    identifier: "build/latest/centos-stream"
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-9
      - centos-stream-10
      - rhel-8
      - rhel-9

  - job: tests
    trigger: pull_request
    packages: [yggdrasil-centos]
    identifier: "unit/centos-stream"
    targets:
      - centos-stream-9
      - centos-stream-10
    labels:
      - unit

  - job: tests
    trigger: pull_request
    packages: [yggdrasil-fedora]
    identifier: "unit/fedora"
    targets:
      - fedora-all
    labels:
      - unit

  - job: tests
    trigger: pull_request
    packages: [yggdrasil-centos]
    identifier: "unit/rhel"
    targets:
      rhel-8-x86_64:
        distros:
          - RHEL-8-Nightly
      rhel-9-x86_64:
        distros:
          - RHEL-9-Nightly
    labels:
      - unit
    use_internal_tf: true

  - job: propose_downstream
    trigger: release
    packages: [yggdrasil-centos]
    dist_git_branches:
      - c10s

  - job: propose_downstream
    trigger: release
    packages: [yggdrasil-fedora]
    dist_git_branches:
      - fedora-branched
