upstream_package_name: yggdrasil
downstream_package_name: yggdrasil
specfile_path: builddir/dist/srpm/yggdrasil.spec

srpm_build_deps:
  - bash-completion
  - gawk
  - git-core
  - golang
  - go-rpm-macros
  - meson
  - "pkgconfig(dbus-1)"
  - "pkgconfig(systemd)"
  - rpm-build

actions:
  post-upstream-clone:
    - meson setup builddir -Dbuild_srpm=True -Dvendor=True -Dexamples=True --wipe
    - meson compile tarball -C builddir
  get-current-version:
    - awk '/^Version:/ {print $2;}' builddir/dist/srpm/yggdrasil.spec
  create-archive:
    - bash -c 'echo builddir/dist/srpm/yggdrasil-*.tar.*'
  fix-spec-file:
    - bash -c 'echo "No action needed"'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-8
      - centos-stream-9
      - fedora-all
      - rhel-8
      - rhel-9

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-8
      - centos-stream-9
      - fedora-all
      - rhel-8
      - rhel-9

  - job: tests
    trigger: pull_request
    identifier: "unit/centos-stream"
    targets:
      - centos-stream-8
      - centos-stream-9
    labels:
      - unit

  - job: tests
    trigger: pull_request
    identifier: "unit/fedora"
    targets:
      - fedora-all
    labels:
      - unit

  - job: tests
    trigger: pull_request
    identifier: "unit/rhel"
    targets:
      rhel-8-x86_64:
        distros:
          - RHEL-8-Nightly
      rhel-9-x86_64:
        distros:
          - RHEL-9-Nightly
    labels:
      - unit
    use_internal_tf: true
