upstream_package_name: yggdrasil
downstream_package_name: rhc
specfile_path: rhc.spec

srpm_build_deps:
  - bash-completion
  - gawk
  - git-core
  - golang
  - rpm-build
  - "pkgconfig(systemd)"

actions:
  post-upstream-clone:
    - curl -O https://raw.githubusercontent.com/RedHatInsights/rhc/refs/heads/release-0.2/rhc.spec.in
    - bash -c "make LONGNAME=rhc BRANDNAME=rhc SHORTNAME=rhc PKGNAME=rhc rhc.spec"
  get-current-version:
    - awk '/^VERSION/ {print $3;}' Makefile
  create-archive:
    - curl -LO https://github.com/RedHatInsights/rhc/releases/download/0.2.6/rhc-0.2.6.tar.gz
    - curl -LO https://github.com/RedHatInsights/yggdrasil-worker-package-manager/releases/download/0.1.0/yggdrasil-worker-package-manager-0.1.0.tar.gz
    - make dist
    - bash -c "echo yggdrasil-${PACKIT_PROJECT_VERSION}.tar.gz"
  fix-spec-file:
    - bash -c "sed -i -r \"s/Source1:.*/Source1:\ yggdrasil-${PACKIT_PROJECT_VERSION}.tar.gz/\" rhc.spec"
    - bash -c "sed -i -r \"s#cd %\{_builddir\}/%\{name\}/yggdrasil-0.2.2#cd %\{_builddir\}/%\{name\}/yggdrasil-${PACKIT_PROJECT_VERSION}#g\" rhc.spec"

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-8
      - centos-stream-9
      - rhel-8
      - rhel-9

  - job: copr_build
    trigger: commit
    branch: yggdrasil-0.2
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-8
      - centos-stream-9
      - rhel-8
      - rhel-9
