#!/bin/bash

export CGO_ENABLED=0

# x86_64
sudo GOPROXY=proxy.golang.org,direct PWD=$PWD spec=$PWD outdir=$PWD make -f .copr/Makefile srpm
sudo rm -rf /root/rpmbuild/*
rpm -ihv `ls -ltr yggdrasil-*.src.rpm | tail -n 1 | awk '{print $NF}'`
rpmbuild -bb ~/rpmbuild/SPECS/yggdrasil.spec
mv `ls -ltr ~/rpmbuild/RPMS/x86_64/yggdrasil*.rpm | tail -n 1 | awk '{print $NF}'` $PWD

# aarch64
sudo GOPROXY=proxy.golang.org,direct PWD=$PWD spec=$PWD outdir=$PWD ARCH=aarch64 make -f .copr/Makefile srpm
sudo rm -rf /root/rpmbuild/*
rpm -ihv `ls -ltr yggdrasil-*.src.rpm | tail -n 1 | awk '{print $NF}'`
# Turn ELF binary stripping off in %post
sed -i '1s/^/%global __os_install_post %{nil}/' ~/rpmbuild/SPECS/yggdrasil.spec
rpmbuild -bb ~/rpmbuild/SPECS/yggdrasil.spec --target aarch64
mv `ls -ltr ~/rpmbuild/RPMS/aarch64/yggdrasil*.rpm | tail -n 1 | awk '{print $NF}'` $PWD
