name: Go

on:
  push:
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18", "1.19"]
    steps:
      - name: Updating ...
        run: sudo apt-get -qq update

      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Go build (source)
        run: go build -v ./...

      - name: Go build (tests)
        run: go test -v ./...

      - name: Go vet
        run: go vet -v ./...
